#!/usr/bin/perl -w
################################################################################
## MARK -- emphasizes part matching a pattern
##
## - It behaves like the filter program.
## - The back and forth 5 lines are displayed in default.
##
## - $Revision: 2.13 $
##
## - Author: 2006-2026, tomyama
## - Intended primarily for personal use, but BSD license permits redistribution.
##
## BSD 2-Clause License:
## Copyright (c) 2006-2026, tomyama
## All rights reserved.
################################################################################

use strict;                         # first released with perl 5
use warnings;                       # first released with perl v5.6.0
use File::Basename qw();            # first released with perl 5
use Getopt::Long qw();              # first released with perl 5

##########
## スクリプトのエントリポイント
sub pl_main( @ )
{

    ## 初期化処理
    init_script();

    ## 引数解析
    if( parse_arg( @_ ) ){
        return 1;
    }

    ## デバッグ用 : パラメータ出力
    if( $main::debug ){
        prt_param();
    }

    if( $main::help || $main::version ){
        if( $main::help ){
            $main::help = 0;
            usage( 0 );
        }
        if( $main::version ){
            $main::version = 0;
            PrintVersion();
        }
        return 0;
    }

#    STDIN->autoflush(1);

    my $file_num = scalar( @main::fi_in );
    my $file_name_len_max = 0;
    my $num_char_disp_area = 8;
    if( $main::prt_fname ){
        for( my $file_idx=0; $file_idx<$file_num; $file_idx++ ){
            my $cur_len = length( $main::fi_in[ $file_idx ] );
            $file_name_len_max = ( $cur_len > $file_name_len_max ? $cur_len : $file_name_len_max );
        }
        $num_char_disp_area = ( ( ( int( $file_name_len_max / 8 ) ) + 1 ) * 8 ) - 1;
    }
    for( my $file_idx=0; $file_idx<$file_num; $file_idx++ ){
        my $opn_fname = $main::fi_in[ $file_idx ];

        if( $main::debug ){
            print STDERR ( qq{ ***** [ $opn_fname ] *****\n});
        }

        open( FI_IN, "<$opn_fname" ) ||
            die( qq{$main::appname: error: "$opn_fname": could not open file: $!\n} );
        my $re_flag = '';
        $re_flag .= 'i' if( $main::ignorecase );
        #print( qq{\$re_flag="$re_flag"\n} );
        my @lines = <FI_IN>;
        my $line_len = scalar( @lines );
        my $line_max = $line_len;   # 行番号は1から始まるので行数と最後の行番号は同じになる
        for(my $idx=0; $idx<$line_len; $idx++ ){
            my $nr = $idx + 1;
            my $mybuff = $lines[ $idx ];
            $mybuff =~ s/\r?\n$//o;

            ## マーキングする
            my $match_flg = 0;
            if( defined( $main::re ) ){
                if( $main::bUseAnsiEscSeqColor ){
                    # インライン修飾子 (?imsx) を埋め込んだ正規表現
                    if( $mybuff =~ s/(?$re_flag)($main::re)/\033[1m$1\033[0m/g ){
                        $match_flg = 1;
                    }
                }else{
                    # インライン修飾子 (?imsx) を埋め込んだ正規表現
                    if( $mybuff =~ m/(?$re_flag)$main::re/g ){
                        $match_flg = 1;
                    }
                }
            }

            if( $main::flag_head_tail ){
                if( ( $nr == 1 ) || ( $nr == $line_max ) ){
                    $match_flg = 1;
                }
            }

            ## マッチしていなかったら
            if( $main::flag_filter && ! $match_flg ){
                ## 後方行の出力
                $main::post_buffer_counter--;
                if( $main::post_buffer_counter >= 0 ){
                    goto PRINTOUT;
                }

                ## 前方行をバッファに溜めておく
                ## buffer_pre=0 の場合はバッファは必要無し
                if( $main::buffer_pre == 0 ){
                    next;
                ## バッファが満杯であれば整理しておく
                }elsif( scalar( @main::pre_buffer ) >= $main::buffer_pre ){
                    shift( @main::pre_buffer );
                }

                ## バッファに溜める
                push( @main::pre_buffer, $mybuff );
                next;
            ## マッチしていたら
            }elsif( $main::flag_filter ){
                ## 読み易いように、skip...を出力
                if( $main::post_buffer_counter + scalar( @main::pre_buffer ) < 0 ){
                    if( $main::bUseAnsiEscSeqColor ){
                        print( "        \033[34m*** skip ***\033[0m\n" );
                    }else{
                        print( "        *** skip ***\n" );
                    }
                }

                ## バッファを吐き出す
                my $pre_buffer_size = scalar( @main::pre_buffer );
                my $nr_first = $nr - $pre_buffer_size;
                for( my $pre_buffer_idx=0; $pre_buffer_idx<$pre_buffer_size; $pre_buffer_idx++ ){
                    ## 必要に応じてファイル名を出力
                    if( $main::prt_fname ){
                        printf( "%-${num_char_disp_area}s:", $opn_fname );
                    }
                    ## 必要に応じて行番号を出力
                    if( $main::numbering ){
                        printf( "%7d:", $nr_first + $pre_buffer_idx ) ;
                    }
                    ## 出力する
                    print( "$main::pre_buffer[ $pre_buffer_idx ]\n" );
                }
                @main::pre_buffer = ();
#                undef( @main::pre_buffer );

                ## 後方行出力用のカウンタをセットする
                $main::post_buffer_counter = $main::buffer_post;
            }

            PRINTOUT:
            ## 必要に応じてファイル名を出力
            if( $main::prt_fname ){
                printf( "%-${num_char_disp_area}s:", $opn_fname );
            }
            ## 必要に応じて行番号を出力
            if( $main::numbering ){
                printf( "%7d:", $nr );
            }
            ## 出力する
            print( "$mybuff\n" );
        }
        close( FI_IN );
    }

    return 0;
}

##########
## 初期化処理
## Revision: 1.3
sub init_script()
{
    my $exec_file = $0;
    $exec_file =~ s!^.*tests/(.*)\.t$!$1!;

    ### GLOBAL ###
    $main::apppath = File::Basename::dirname( $exec_file );
    $main::appname = File::Basename::basename( $exec_file );
    $main::argc = 0;
    $main::debug = 0;
    $main::numbering = 0;
    $main::prt_fname = undef;
    $main::help = 0;
    $main::version = 0;
    $main::flag_head_tail = 0;
    $main::flag_filter = 0;
    $main::buffer_pre  = 5;
    $main::buffer_post = 5;
    @main::pre_buffer = ();
    $main::post_buffer_counter = 0;
    $main::ignorecase = 0;
    $main::re = undef;
    @main::fi_in = ();
    ## ［ANSIエスケープシーケンス］を使うか否かの判定で使う
    $main::bUseAnsiEscSeqColor = -t STDOUT;
    ##############
}

##########
## デバッグ用 : パラメータ出力
sub prt_param()
{
    printf STDERR ( qq{ ***** PARAMETER *****\n} .
                   qq{\$main::apppath = "$main::apppath"\n} .
                   qq{\$main::appname = "$main::appname"\n} .
                   qq{\$main::argc = $main::argc\n} .
                   qq{\$main::debug = $main::debug\n} .
                   qq{\$main::bUseAnsiEscSeqColor = $main::bUseAnsiEscSeqColor\n} .
                   qq{\$main::numbering = $main::numbering\n} .
                   qq{\$main::prt_fname = %s\n} .
                   qq{\$main::flag_head_tail = $main::flag_head_tail\n} .
                   qq{\$main::flag_filter = $main::flag_filter\n} .
                   qq{\$main::buffer_pre = $main::buffer_pre\n} .
                   qq{\$main::buffer_post = $main::buffer_post\n} .
                   qq{scalar( \@main::pre_buffer ) = %d\n} .
                   qq{\$main::post_buffer_counter = $main::post_buffer_counter\n} .
                   qq{\$main::ignorecase = $main::ignorecase\n} .
                   qq{\$main::re = %s\n} .
                   qq{\@main::fi_in = (%s)\n},
                   defined( $main::prt_fname ) ? qq{"$main::prt_fname"} : 'undef',
                   scalar( @main::pre_buffer ),
                   defined( $main::re ) ? qq{"$main::re"} : 'undef',
                   array_to_str( @main::fi_in ) );
}

sub array_to_str( @ )
{
    return q{ '} . join( q{', '}, @_ ) . q{' } if( scalar( @_ ) > 0 );
    return '';
}

##########
## 引数解析
sub parse_arg( @ )
{
    @main::argv = @_;
    $main::argc = scalar( @main::argv );

    # Getopt::Long が動くように局所的に変更して騙す
    local @ARGV = @main::argv;

    # 設定: ショートオプションのまとめ指定（バンドリング）を有効化
    Getopt::Long::Configure("bundling");

    Getopt::Long::GetOptions(
        'debug|d'   => \$main::debug,
        'head-tail' => sub{
            $main::flag_head_tail = 1;
            $main::flag_filter = 1;
        },
        'f:s' => sub{
            my( $optname, $arg ) = @_;
            $main::flag_filter = 1;
            #print( qq{f arg: "$arg"\n} );

            if( $arg =~ m/^(\d+)(?:,(\d+))?$/o ){
                $main::buffer_pre  = $1;
                $main::buffer_post = $1;
                if( defined( $2 ) ){
                    $main::buffer_post = $2;
                }
            }else{
                push( @ARGV, $arg );
            }
        },
        'with-filename|H' => \$main::prt_fname,
        'no-filename|h' => sub{ $main::prt_fname = 0; },
        'help'          => \$main::help,
        'version|v'     => \$main::version,
        'ignore-case|i' => \$main::ignorecase,
        'line-number|n' => \$main::numbering,
        'force-color|c' => \$main::bUseAnsiEscSeqColor,
        'NON-EXISTENT-FILE' => sub{ push( @main::fi_in, 'NON-EXISTENT-FILE' ) },
    ) || die( qq{parse_arg(): error: Failed to parse option switches.\n} );

    if( $main::help || $main::version ){
        return 0;
    }

    while( my $myparam = shift( @ARGV ) ){
        #print( qq{\$myparam = "$myparam"\n} );
        if( $myparam eq '-' ){
            my $fi_in_len = scalar( @main::fi_in );
            for( my $idx=0; $idx<$fi_in_len; $idx++ ){
                if( $main::fi_in[ $idx ] eq '-' ){
                    myerr( qq{"STDIN(-)" cannot be specified more than once.\n} );
                    return 1;
                }
            }
            push( @main::fi_in, $myparam );
        }elsif( -f $myparam ){
            push( @main::fi_in, $myparam );
        }else{
            if( defined( $main::re ) ){
                myerr( qq{"$myparam": <PATTERN> has already been specified as "$main::re".\n} );
                return 1;
            }else{
                $main::re = $myparam;
            }
        }
    }

    my $fi_in_nums = scalar( @main::fi_in );

    if( ( !defined( $main::re ) ) && ( $main::flag_head_tail == 0 ) ){
        if( $fi_in_nums > 0 ){
            $main::re = shift( @main::fi_in );
            $fi_in_nums--;
        }else{
            myerr( qq{Please specify <PATTERN>.\n} );
            usage( 1 );
            return 1;
        }
    }

    if( $fi_in_nums == 0 ){
        push( @main::fi_in, '-' );
    }
    if( !defined( $main::prt_fname ) ){
        if( $fi_in_nums > 1 ){
            $main::prt_fname = 1;
        }else{
            $main::prt_fname = 0;
        }
    }

    return 0;
}

#sub mywarn()
#{
#    warn( qq{$main::appname: warn: }, @_ );
#}

sub myerr()
{
    warn( qq{$main::appname: error: }, @_ );
}

## Revision: 1.2
sub PrintVersion()
{
    my $ver = GetVersion();
    my $v = qq{Version: $ver\n} .
            qq{   Perl: $^V\n};
    print( $v );
}
sub GetVersion()
{
    my $rev = GetRevision();

    my $major = 1;
    my( $minor, $revision ) = split( /\./, $rev );
    my $version = sprintf( '%d.%02d.%03d', $major, $minor, $revision );

    return $version;
}
sub GetRevision()
{
    my $rev = q{$Revision: 2.13 $};
    $rev =~ s!^\$[R]evision: (\d+\.\d+) \$$!$1!o;
    return $rev;
}

##########
## 書式表示
## Revision: 1.2
sub usage( $ )
{
    my $msg = "Usage:\n" .
        qq{  $main::appname [<OPTIONS...>] <PATTERN> [<FILE...>]\n} .
        qq{  $main::appname --head-tail [<OPTIONS...>] [<PATTERN>] [<FILE...>]\n} .
        qq{\n} .
        qq{The "mark" utility behaves like a marker pen.\n} .
        qq{It searches for the specified PATTERN and emphasizes matching text.\n} .
        qq{\n} .
        qq{<PATTERN>: A Perl-compatible regular expression (PCRE).\n} .
        qq{<FILE>   : Input file name. Use "-" for standard input (stdin).\n} .
        qq{\n} .
        qq{<OPTIONS>\n} .
        qq{  -f [before[,after]]:\n} .
        qq{    Filter mode. Displays context lines before and after the match.\n} .
        qq{    Defaults to 5 lines before and after if values are omitted.\n} .
        qq{    If 0 is specified, only the matching lines are displayed.\n} .
        qq{\n} .
        qq{  --head-tail\n} .
        qq{    Display mode. Shows only the beginning and end of the file.\n} .
        qq{    Automatically enables filter mode (-f). The number of lines displayed\n} .
        qq{    at the top and bottom of the file (or around matches) can be customized\n} .
        qq{    using the '-f' option (e.g., -f 2,3).\n} .
        qq{    When using this option, providing a <PATTERN> is optional.\n} .
        qq{\n} .
        qq{  -h, --no-filename:\n} .
        qq{    Suppress the prefixing of filenames on output when multiple files are searched.\n} .
        qq{  -H, --with-filename:\n} .
        qq{    Print the filename for each match.\n} .
        qq{  -i, --ignore-case:\n} .
        qq{    Ignore case distinctions in the <PATTERN>.\n} .
        qq{  -n, --line-number:\n} .
        qq{    Prefix each line of output with its line number within the file.\n} .
        qq{  -c, --force-color:\n} .
        qq{    Enable highlighting even if STDOUT is not a TTY (e.g., pipes, redirects).\n} .
        qq{  -v, --version:\n} .
        qq{    Print the version of this script and Perl, then exit.\n} .
        qq{  --help:\n} .
        qq{    Display this help and exit.\n} .
        qq{\n} .
        qq{Try "perldoc $main::apppath/$main::appname" for more information.\n};

    if( $_[0] ){
        print STDERR ( $msg );
    }else{
        print STDOUT ( $msg );
    }

    return 0;
}

# uncoverable branch false
exit( pl_main( @ARGV ) ) unless caller();

__END__

=pod

=encoding utf8

=head1 NAME

MARK - emphasizes part matching a pattern

=head1 SYNOPSIS

$ mark [I<OPTIONS...>] I<PATTERN> [I<FILE...>]

=head1 DESCRIPTION

The "B<mark>" behaves like the marker pen.
The specified I<PATTERN> is searched out and that part is emphasized.

The I<PATTERN> can be described by the Regular-Expression equal with B<Perl>.

I<FILE> specifies the input file name.
If it is a standard input, "B<->" is given.

=head1 OPTIONS

=over 4

=item -d, --debug

Debugging mode is on.

=item -f [I<num-forward>[,I<num-rear>]]

It works like a filter program. If you omit the value,
the default is to display 5 lines before and after.
If you specify 0 for I<num>, only lines that match I<PATTERN> will be displayed.
If you specify 0, grep is more convenient.

=item --help

Display simple help and exit.

=item -v, --version

Print the version of this script and Perl and exit.

=item -h, --no-filename

Suppress the prefixing of filenames on output when multiple files are searched.

=item -H, --with-filename

Print the filename for each match.

=item -i, --ignore-case

Ignore case distinctions in the I<PATTERN>.

=item -n, --line-number

Prefix each line of output with the line number within its input file.

=item -c, --force-color

Enable highlighting even if STDOUT is not a TTY (pipe, redirect).

=back

=head1 ADVANCED USAGE

  $ rpm -qa | mark '-[0-9]+[a-z]?\..+$'

  $ mark '\b\d{1,3}(?:\.\d{1,3}){3}\b' /var/log/maillog

  $ mark -nf 5,0 '(ServerName|DocumentRoot|Log)\s+.*$' /etc/httpd/conf/httpd.conf

  $ mark -iHnf 0,10 '^[^\s].*$' *.{c,h}

  $ mark -ni '</?(table|tr|th|td)[^>]*>' index.html | S<less -R>

  $ man perlfunc | mark -nf 5,10 -i 'regular expr' | S<less -R>

  $ man awk | perl -ne 's/.\010//go; print' | S<mark -nf 0,3 '^[A-Z]'>

  $ tail -f /var/log/httpd/access_log | S<mark -f 0 '"(GET|POST) /(?:\S+(?:\.html|\.htm|/))? [^"]+"'>

  $ ls -tr /var/log/messages.?.gz | xargs gzip -dc | mark -ihf 10 'error' - /var/log/messages > /tmp/report.txt

=head1 DEPENDENCIES

This script uses only B<core Perl modules>. No external modules from CPAN are required.

=head2 Core Modules Used

=over 4

=item * L<File::Basename> — first included in perl 5

=item * L<strict> — first included in perl 5

=item * L<warnings> — first included in perl v5.6.0

=back

=head2 Survey methodology

=over 4

=item 1. Preparation

Define the script name:

  $ target_script=mark

=item 2. Extract used modules

Generate a list of modules from C<use> statements:

  $ grep '^use ' $target_script | sed 's!^use \([^ ;{][^ ;{]*\).*$!\1!' | \
      sort | uniq | tee ${target_script}.uselist

=item 3. Check core module status

Run C<corelist> for each module to find the first Perl version it appeared in:

  $ cat ${target_script}.uselist | while read line; do
      corelist $line
    done

=back

=head1 SEE ALSO

When you want to examine the regular expression,
please refer to an online manual of B<Perl>.

=over 4

=item L<C<perlre(1)>>

Perl regular expressions

=item L<C<perlrequick(1)>>

Perl regular expressions quick start

=item L<C<perlreref(1)>>

Perl Regular Expressions Reference

=item L<C<perlretut(1)>>

Perl regular expressions tutorial

=item L<C<perlfaq6(1)>>

Regular Expressions

=item L<C<regex(7)>>

POSIX 1003.2 regular expressions

=back

Other more basic references

=over 4

=item L<C<perl(1)>>

=item L<C<grep(1)>>

=back

=head1 AUTHOR

2006-2026, tomyama

=head1 LICENSE

Copyright (c) 2006-2026, tomyama

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of tomyama nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=cut
