#!/usr/bin/perl -w
##
## Support for environments where the -e option of the echo command does not work.
## ex) Test::Command on Android Termux
##

use strict;
use warnings 'all';

my %escapes = (
    'n' => "\n",   # 改行
    't' => "\t",   # 水平タブ
    'r' => "\\r",   # 復帰
    'f' => "\\f",   # 改ページ
    'a' => "\\a",   # 警報音
    'e' => "\\e",   # ESC
);

my @args = @ARGV;

my $argc = scalar( @args );
if( ( $argc > 0 ) && ( $args[ 0 ] eq '-e' ) ){
    $argc--;
    shift( @args );
}else{
    $args[ $argc - 1 ] .= "\n";
}
for( my $idx=0; $idx<$argc; $idx++ ){
    #print( qq{\$args[ $idx ] = "$args[ $idx ]"\n} );
#    $args[ $idx ] =~ s/\\n/\n/go;
#    $args[ $idx ] =~ s/\\a/\a/go;
    $args[ $idx ] =~ s/\\([ntrfae])/$escapes{ $1 }/go;
    #print( qq{\$args[ $idx ] = "$args[ $idx ]"\n} );
}
print( join( ' ', @args ) );
