#!/usr/bin/env perl
################################################################################
## gen_autotools_input.pl -- Generate and manage autotools "ac" and "am" files from a single source.
##
## - Outputs autotools ac and am files based on the data in "GenAutotoolsInput_UserFile.pm".
## - Eliminates the hassle of adding definitions to multiple files.
##
## - If any files have been updated, it will exit with 0.
## - If no files have been updated, it will exit with a value other than 0.
##
## - $Revision: 1.16 $
##
## - Author: 2025-2026, tomyama
## - Intended primarily for personal use, but BSD license permits redistribution.
##
## BSD 2-Clause License:
## Copyright (c) 2025-2026, tomyama
## All rights reserved.
################################################################################

use strict;                         # first released with perl 5
use warnings;                       # first released with perl v5.6.0
use File::Basename qw();            # first released with perl 5

use lib './tools';    # @INC にディレクトリを追加
use GenAutotoolsInput_UserFile;

my $apppath;
my $appname;

my $exit_status = 1;

exit( &pl_main( @ARGV ) );


## スクリプトのエントリポイント
sub pl_main( @ )
{
    &initialize( @_ );  ## 初期化処理
    &parse_arg( @_ );   ## 引数解析

    GenAutotoolsInput_UserFile::setupValue();
    my %ACAM_KYVL = GenAutotoolsInput_UserFile::getKeyValue();
    my $pkg_uniq_ID = GenAutotoolsInput_UserFile::getPkgUniqID();
    my %ACAM_TMPL = GenAutotoolsInput_UserFile::getTemplates();

    foreach my $kv_k( sort( keys( %ACAM_KYVL ) ) ){
        print( qq{"$kv_k" = "$ACAM_KYVL{ $kv_k }"\n} );
    }

    foreach my $k( sort( keys( %ACAM_TMPL ) ) ){
        my $newfile_body = $ACAM_TMPL{ $k };

        foreach my $kv_k( sort( keys( %ACAM_KYVL ) ) ){
#            print( qq{"$kv_k" = "$ACAM_KYVL{ $kv_k }"\n} );
            if( ! ( $kv_k =~ m/^\$[^\$]+\$$/o ) ){
#                print( qq{"$kv_k" = "$ACAM_KYVL{ $kv_k }": skip\n} );
                next;
            }
            $newfile_body =~ s!\Q$kv_k\E!$ACAM_KYVL{ $kv_k }!g;
        }

        ## コメントで始まる行は削除
        my @lines = split( /\r?\n/, $newfile_body );
        $newfile_body = qq{# [$k] is auto-generated by `tools/gen_autotools_input.pl`.\n} .
                        qq{# Do not edit manually.\n} .
                        qq{# Base file: [GenAutotoolsInput_UserFile] is "$pkg_uniq_ID".\n};

        my $line_len = scalar( @lines );
        for( my $idx=0; $idx<$line_len; $idx++ ){
            my $l = $lines[ $idx ];
            if( $l =~ m/^(?:dnl|#)/io ){
                next;
            }

            $newfile_body .= $l . "\n";
        }

#        print( qq{[$k]\n} );
#        print( qq{$newfile_body} );

        my $bOldFileNothing = 0;
        if( ! -f $k ){
            $bOldFileNothing = 1;
            print( qq{$appname: $k: file not found: create!\n} );
        }

        my $newfile = "$k.new";
        open( NEWFILE, '>', $newfile ) ||
            die( qq{$appname: $newfile: could not open file: $!} );
        print NEWFILE ( $newfile_body );
        close( NEWFILE );

        my $diff = '';
        if( $bOldFileNothing ){
            $diff = 'dummy: If the file does not exist, create it.';
        }else{
            open( EXISTS_FILE, '<', $k ) ||
                die( qq{"$k": could not open file: $!} );
            my @body = <EXISTS_FILE>;
            close( EXISTS_FILE );
            my $exists_body = join( "", @body );
            #print( qq{\$exists_body = "\n$exists_body"\n} );
            $diff = '$exists_body is not $newfile_body.' if( $exists_body ne $newfile_body );
        }

        if( $diff eq '' ){
            print( qq{[$k] The file is already up to date.\n} );
            if( unlink( $newfile ) <= 0 ){
                print STDERR ( qq{$appname: could not remove file: $newfile\n} );
            }
        }else{
            if( $bOldFileNothing ){
                print( qq{[$k] Needs to be created.\n} );
                if( unlink( $k ) <= 0 ){
                    print STDERR ( qq{$appname: could not remove file: $k\n} );
                }
            }else{
                print( qq{[$k] Update required.\n} );
            }
            $exit_status = 0;
            rename( $newfile, $k ) ||
                die( qq{$appname: could not rename file: $newfile -> $k\n} );
            system( 'cat', '-n', "$k" );
        }
    }

    return $exit_status;
}

## 初期化サブルーチン
sub initialize( @ )
{
    ### GLOBAL ###
    $apppath = File::Basename::dirname( $0 );
    $appname = File::Basename::basename( $0 );
    $main::debug = 0;
    ##############

    return 0;
}

## 引数解析
sub parse_arg( @ )
{
    my @val = @_;

    ## 引数分のループを回す
    while( my $myparam = shift( @val ) ){
        if( $myparam =~ s/^-([a-zA-Z])([a-zA-Z]+)$/-$1/o ){
            unshift( @val, "-$2" );
        }

        ## デバッグモードOn
        if    ( $myparam eq '-d' || $myparam eq '--debug' ){
            $main::debug = 1;
        }elsif( $myparam eq '-h' || $myparam eq '--help' ){
            &usage( 0 );
            exit( 0 );
        }else{
            print STDERR ( qq{$appname: `$myparam': Unknown option\n} );
        }
        print STDERR ( qq{ARGV : "$myparam"\n} ) if( $main::debug );
    }

    return 0;
}

## 書式表示
sub usage( $ )
{
    my $msg = "Usage: " .
    "$appname [<OPTIONS...>]\n" .
    "Try `perldoc $apppath/$appname' for more information.\n";

    if( $_[0] ){
        print STDERR ( $msg );
    }else{
        print STDOUT ( $msg );
    }

    return 0;
}
__END__

=pod

=head1 NAME

gen_autotools_input.pl -- Generate and manage autotools "ac" and "am" files from a single source.

=head1 VERSION

This document describes $Revision: 1.16 $.

=head1 SYNOPSIS

$ gen_autotools_input.pl [I<OPTIONS...>]

=head1 DESCRIPTION

This script generates and updates autotools "ac" and "am" files
based on templates and key-value pairs defined in "GenAutotoolsInput_UserFile.pm".
It helps avoid the need to duplicate definitions across multiple files.

If any files have been updated, it will exit with 0.
If no files have been updated, it will exit with a value other than 0.

Example:

  $ ls -1 tools/*.p?
  tools/GenAutotoolsInput_UserFile.pm
  tools/gen_autotools_input.pl
  $ ./tools/gen_autotools_input.pl

The file "tools/GenAutotoolsInput_UserFile.pm" defines templates such as "configure.ac".
Hash keys correspond to relative paths from the project root.
For example, the key for "tests/Makefile.am" is simply "tests/Makefile.am".

Note: This script must be executed from the project root,
otherwise "tools/GenAutotoolsInput_UserFile.pm" will not be found.

=head1 OPTIONS

=over 4

=item B<-d>, B<--debug>

Enable debugging mode.

=item B<-h>, B<--help>

Show a brief usage message.

=back

=head1 SEE ALSO

L<GenAutotoolsInput_UserFile.pm>, perl(1)

=head1 AUTHOR

2025-2026, tomyama

=head1 LICENSE

Copyright (c) 2025-2026, tomyama

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of tomyama nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=cut
